######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 26 20:54:32 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/s/a/sambeau/Desktop/EC535/Project/qt/. .

# Input
HEADERS += gui.h
SOURCES += gui.cpp main.cpp
